import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { resolve } from "node:path";

const require = createRequire(import.meta.url);
const { Midi } = require("@tonejs/midi") as typeof import("@tonejs/midi");

export type MidiBeatNote = {
  midi: number;
  startBeat: number;
  durationBeats: number;
  velocity: number;
  sourceId?: number;
};

export type ExtractedMidiNote = {
  midi: number;
  startBeat: number;
  durationBeats: number;
  dynamic: number;
};

export type MidiImportConfig = {
  songId: string;
  input: string;
  output: string;
  sourceTrack: number;
  sourceBeats: readonly [number, number];
  transposeSemitones: number;
  melodyStrategy: "skyline" | "monophonic-track";
  phraseBeats: number;
  sha256: string;
};

export type MidiImportManifest = {
  version: 1;
  pieces: MidiImportConfig[];
};

export type GeneratedMidiNote = ExtractedMidiNote & {
  phrase: number;
};

export type MidiImportResult = {
  sha256: string;
  sourceTrack: number;
  parsedTrackIndex: number;
  rawNoteCount: number;
  notes: GeneratedMidiNote[];
};

export async function importMidiPiece(
  projectRoot: string,
  config: MidiImportConfig,
): Promise<MidiImportResult> {
  const bytes = await readFile(resolve(projectRoot, config.input));
  const sha256 = createHash("sha256").update(bytes).digest("hex");
  if (sha256 !== config.sha256.toLowerCase()) {
    throw new Error(
      `SHA-256 mismatch for ${config.input}: expected ${config.sha256}, received ${sha256}`,
    );
  }

  if (!Number.isInteger(config.sourceTrack) || config.sourceTrack < 1) {
    throw new Error("sourceTrack must use a one-based SMF track number");
  }
  const [sourceStart, sourceEnd] = config.sourceBeats;
  if (sourceStart < 0 || sourceEnd <= sourceStart) {
    throw new Error("sourceBeats must define an increasing range");
  }
  if (config.phraseBeats <= 0) {
    throw new Error("phraseBeats must be positive");
  }

  const midi = new Midi(bytes);
  const parsedTrackIndex = config.sourceTrack - 1;
  const track = midi.tracks[parsedTrackIndex];
  if (!track) {
    throw new Error(
      `SMF track ${config.sourceTrack} is unavailable in ${config.input}`,
    );
  }

  const ppq = midi.header.ppq;
  const rawNotes: MidiBeatNote[] = track.notes.flatMap((note, sourceId) => {
    const noteStart = note.ticks / ppq;
    const noteEnd = (note.ticks + note.durationTicks) / ppq;
    const clippedStart = Math.max(sourceStart, noteStart);
    const clippedEnd = Math.min(sourceEnd, noteEnd);
    const quantizedStart = Math.max(sourceStart, quantizeBeat(clippedStart));
    const quantizedEnd = Math.min(sourceEnd, quantizeBeat(clippedEnd));
    if (quantizedEnd <= quantizedStart) return [];

    return [{
      midi: note.midi,
      startBeat: roundToThousandth(quantizedStart - sourceStart),
      durationBeats: roundToThousandth(quantizedEnd - quantizedStart),
      velocity: note.velocity,
      sourceId,
    }];
  });

  const extracted = config.melodyStrategy === "skyline"
    ? extractSkyline(rawNotes)
    : extractMonophonicTrack(rawNotes);
  const notes = extracted.map((note) => {
    const midi = note.midi + config.transposeSemitones;
    if (!Number.isInteger(midi) || midi < 0 || midi > 127) {
      throw new Error(`Transposed MIDI note is out of range: ${midi}`);
    }
    return {
      midi,
      startBeat: note.startBeat,
      durationBeats: note.durationBeats,
      dynamic: roundToThousandth(clamp01(note.dynamic)),
      phrase: Math.floor(note.startBeat / config.phraseBeats),
    };
  });

  return {
    sha256,
    sourceTrack: config.sourceTrack,
    parsedTrackIndex,
    rawNoteCount: rawNotes.length,
    notes,
  };
}

export function renderGeneratedMelody(
  config: MidiImportConfig,
  result: MidiImportResult,
): string {
  const constantName = `${config.songId.replaceAll("-", "_").toUpperCase()}_MELODY`;
  const noteLines = result.notes.map((note) =>
    [
      "  {",
      `midi: ${note.midi},`,
      `startBeat: ${formatNumber(note.startBeat)},`,
      `durationBeats: ${formatNumber(note.durationBeats)},`,
      `dynamic: ${formatNumber(note.dynamic)},`,
      `phrase: ${note.phrase}`,
      "},",
    ].join(" ")
  );

  return [
    "// Generated by pnpm music:import. Do not edit by hand.",
    `// Source: ${config.input}`,
    `// SHA-256: ${result.sha256}`,
    "",
    'import type { SongNote } from "../songTypes";',
    "",
    `export const ${constantName}: SongNote[] = [`,
    ...noteLines,
    "];",
    "",
  ].join("\n");
}

const EPSILON = 1e-9;

export function quantizeBeat(beat: number): number {
  return roundToThousandth(Math.round(beat * 2) / 2);
}

export function extractSkyline(notes: MidiBeatNote[]): ExtractedMidiNote[] {
  const usable = notes
    .filter((note) => note.durationBeats > 0)
    .map((note, sourceId) =>
      normalizeInputNote({ ...note, sourceId: note.sourceId ?? sourceId })
    );
  const boundaries = [...new Set(
    usable.flatMap((note) => [
      note.startBeat,
      note.startBeat + note.durationBeats,
    ]),
  )].sort((a, b) => a - b);

  const intervals: Array<ExtractedMidiNote & { sourceId: number }> = [];
  for (let index = 0; index < boundaries.length - 1; index += 1) {
    const startBeat = boundaries[index]!;
    const endBeat = boundaries[index + 1]!;
    if (endBeat - startBeat <= EPSILON) continue;

    const active = usable
      .filter((note) =>
        note.startBeat <= startBeat + EPSILON
        && note.startBeat + note.durationBeats >= endBeat - EPSILON
      )
      .sort((a, b) => b.midi - a.midi || b.velocity - a.velocity);

    const selected = active[0];
    if (!selected) continue;
    intervals.push({
      midi: selected.midi,
      startBeat,
      durationBeats: roundToThousandth(endBeat - startBeat),
      dynamic: clamp01(selected.velocity),
      sourceId: selected.sourceId!,
    });
  }

  return mergeSkylineIntervals(intervals);
}

export function extractMonophonicTrack(
  notes: MidiBeatNote[],
): ExtractedMidiNote[] {
  const sorted = notes
    .filter((note) => note.durationBeats > 0)
    .map(normalizeInputNote)
    .sort((a, b) => a.startBeat - b.startBeat || a.midi - b.midi);

  sorted.forEach((note, index) => {
    const previous = sorted[index - 1];
    if (
      previous
      && note.startBeat < previous.startBeat + previous.durationBeats - EPSILON
    ) {
      throw new Error(
        `MIDI overlap between notes ${index - 1} and ${index}`,
      );
    }
  });

  return mergeAdjacentEqualPitches(
    sorted.map((note) => ({
      midi: note.midi,
      startBeat: note.startBeat,
      durationBeats: note.durationBeats,
      dynamic: clamp01(note.velocity),
    })),
  );
}

function mergeSkylineIntervals(
  notes: Array<ExtractedMidiNote & { sourceId: number }>,
): ExtractedMidiNote[] {
  const merged: Array<ExtractedMidiNote & { sourceId: number }> = [];

  notes.forEach((note) => {
    const previous = merged.at(-1);
    if (
      previous
      && previous.sourceId === note.sourceId
      && previous.midi === note.midi
      && Math.abs(
        previous.startBeat + previous.durationBeats - note.startBeat,
      ) <= EPSILON
    ) {
      previous.durationBeats = roundToThousandth(
        previous.durationBeats + note.durationBeats,
      );
      previous.dynamic = Math.max(previous.dynamic, note.dynamic);
      return;
    }
    merged.push({ ...note });
  });

  return merged.map(({ sourceId: _sourceId, ...note }) => note);
}

function mergeAdjacentEqualPitches(
  notes: ExtractedMidiNote[],
): ExtractedMidiNote[] {
  const merged: ExtractedMidiNote[] = [];

  notes.forEach((note) => {
    const previous = merged.at(-1);
    if (
      previous
      && previous.midi === note.midi
      && Math.abs(
        previous.startBeat + previous.durationBeats - note.startBeat,
      ) <= EPSILON
    ) {
      previous.durationBeats = roundToThousandth(
        previous.durationBeats + note.durationBeats,
      );
      previous.dynamic = Math.max(previous.dynamic, note.dynamic);
      return;
    }
    merged.push({ ...note });
  });

  return merged;
}

function normalizeInputNote(note: MidiBeatNote): MidiBeatNote {
  return {
    midi: Math.round(note.midi),
    startBeat: roundToThousandth(note.startBeat),
    durationBeats: roundToThousandth(note.durationBeats),
    velocity: clamp01(note.velocity),
    sourceId: note.sourceId,
  };
}

function clamp01(value: number): number {
  return Math.min(1, Math.max(0, value));
}

function formatNumber(value: number): string {
  return String(roundToThousandth(value));
}

function roundToThousandth(value: number): number {
  return Math.round(value * 1000) / 1000;
}
